telegram_token: "6775532815:AAGF1ou6Hi6j4x8MsW-phCRxJn2cY3q5mGk"
openai_api_key: "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"
openai_api_base: null  # leave null to use default api base or you can put your own base url here
allowed_telegram_usernames: [5289366783]  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # 会话超时时间
n_chat_modes_per_page: 5
#生成图片
image_count: 1 #返回生成的图片数量
image_quality: "standard" #图像质量 standard hd
image_style: "vivid" #图像风格
image_size: "1024x1024" #512x512 1024x1024 1024x1792 1792x1024
#解释图片
vision_detail: "auto" #解释图片质量 low,high,auto
vision_prompt: "图片里有什么？如果图片里有人请告诉我是谁，如果图片里地点请告诉我地点"
#文字转语音
tts_voice: "alloy" #语音风格 alloy echo fable onyx nova shimmer
tts_voice_formats: "opus" #语音格式 mp3 opus aac flac

context_len: 5 #上下文长度
