available_text_models: ["gpt-3.5-turbo-16k", "gpt-4-1106-preview", "gpt-4-vision-preview"]
available_image_models: ["dall-e-2", "dall-e-3"]
available_audio_models: ["tts-1", "tts-1-hd"]

info:
  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-3.5-Turbo
    price_per_1000_input_tokens: 0.001
    price_per_1000_output_tokens: 0.002

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4-Turbo
    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4-Vision
    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

  dall-e-2:
     type: image
     name: DALL-E-2
     price_per_1_image: 0.02  # 1024x1024

  dall-e-3:
     type: image
     name: DALL-E-3
     price_per_1_image: 0.04  # 1024x1024

  whisper:
    type: audio
    name: Whisper
    price_per_1_min: 0.006
  
  tts-1:
    type: audio
    name: TTS
    price_per_1000_input_tokens: 0.015

  tts-1-hd:
    type: audio
    name: TTS-HD
    price_per_1000_input_tokens: 0.03